config/routes.rb
Rails.application.routes.draw do
  root 'okutama#index'
  resources :okutama, only: [] do
    collection do 
      get 'access'
    end
  end
  resources :contacts, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :email, presence: true, length: {maximum:255},
                    format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i}
  validates :message, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      ContactMailer.contact_mail(@contact).deliver
      flash[:success] = 'お問い合わせを受け付けました'
      redirect_to root_path
    else
      render :new
    end
  end

  
  private
  def contact_params
    params.require(:contact).permit(:name, :email, :message)
  end
end

app/controllers/okutama_controller.rb
class OkutamaController < ApplicationController
  def index
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/new.html.haml
= render '/templates/other_header'
.page-title
  %h2
    CONTACT
.contact-form
  = form_for @contact do |f|
    .input-area
      %p お名前
      .input-area__form
        = f.text_field :name
    .input-area
      %p メールアドレス
      .input-area__form
        = f.email_field :email
    .input-area
      %p お問い合わせ内容
      .input-area__form
        = f.text_area :message
    = f.submit '送信', id: 'contact-button'
= render '/templates/footer'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Okutama
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/okutama/access.html.haml
= render '/templates/other_header'
.page-title
  %h2
    ACCESS
.map-area
  = render '/templates/map'
.how-to-access
  .by-train
    %h3
      電車でのアクセス
    .by-train__text
      %p 東京方面から中央線立川駅で青梅線に乗換、青梅駅で奥多摩行きに乗換
      %p 青梅線 青梅駅〜川井駅まで21分（8駅）
      %p 川井駅より奥多摩日本語学校まで徒歩14分（800m）
    .by-train__image
  .by-car
    %h3
      車でのアクセス
    .by-car__text
      %p ※学校には駐車場20台分程度有り
      %p 東京方面から中央自動車道八王子JCT～圏央道日の出IC～国道411号線～奥多摩町
      %p 埼玉方面から圏央道青梅IC～青梅街道～奥多摩町
    .by-car__image
= render '/templates/footer'

app/views/okutama/index.html.haml
= render '/templates/index_header'
.top-image-container
  .top-image
    = image_tag 'top.png'
.main
  .main__title
    %h1
      新感覚のスパイス使いでインド料理の概念を覆すモダンインディアンキュイジーヌ
  .main__text
    %h2 
      日本人が持つ「インド料理」の概念を覆すモダンインディアンキュイジーヌ（Modern Indean Cuisine）を味わう。SPICE LAB TOKYOでは、洗練されたスパイス使いで新鮮な驚きに溢れる料理とスタイリッシュな上質空間で、世界中でここ銀座でしか体験できない、とっておきのエクスペリアンスをお届けします。
  .main__images
    .main__images--image1
      = link_to '#' do
        .image1
    .main__images--image2
      = link_to '#' do
        .image2
    .main__images--image3
      = link_to '#' do
        .image3
    .main__images--image4
      = link_to '#' do
        .image4
= render '/templates/footer'

app/views/templates/_footer.html.haml
.footer#footer
  .footer__top
    %ul.footer__top--ul
      %li
        = link_to '□'
      %li
        = link_to '□'
  .footer__bottom
    %p
      © 2019 SPICE LAB TOKYO ALL RIGHTS RESERVED.

app/views/templates/_header.html.haml
.header#header
  .header__left
    .header__left--logo
      %h1
        = link_to 'OKUTAMA', root_path
  .header__right
    %ul.header__right--ul
      %li
        = link_to 'PHILOSOPHY'
      %li
        = link_to 'MENU'
      %li
        = link_to 'GALLERY'
      %li
        = link_to 'NEWS'
      %li
        = link_to 'ACCESS'
      %li
        = link_to 'RESERVATION'

app/views/templates/_index_header.html.haml
.header#header
  .header__left
    .header__left--logo
      %h1
        = link_to 'OKUTAMA', root_path
  .header__right
    %ul.header__right--ul
      %li
        = link_to 'PHILOSOPHY'
      %li
        = link_to 'MENU'
      %li
        = link_to 'GALLERY'
      %li
        = link_to 'NEWS'
      %li
        = link_to 'ACCESS', access_okutama_index_path
      %li
        = link_to 'CONTACT', new_contact_path

app/views/templates/_map.html.haml
#map
:css
  #map{
    height: 400px;
    width: 80%;
    max-width: 800px;
    margin: 0 auto;
  }
:javascript
  var map;
  var marker;
  var center = {
        lat: 35.811352,
        lng: 139.158861
      };
  var infoWindow;
  function initMap() {
    map = new google.maps.Map(document.getElementById('map'), {
      center: center,
      zoom: 16
    });
    marker = new google.maps.Marker({ // マーカーの追加
      position: center, // マーカーを立てる位置を指定
      map: map // マーカーを立てる地図を指定
    });
    infoWindow = new google.maps.InfoWindow({ // 吹き出しの追加
        content: '<div class="sample">OKUTAMA</div>' // 吹き出しに表示する内容
    });
    marker.addListener('click', function() { // マーカーをクリックしたとき
     infoWindow.open(map, marker); // 吹き出しの表示
    });
  }
%script{:async => "", :defer => "defer", :src => "https://maps.googleapis.com/maps/api/js?key=#{ENV['GOOGLEMAP']}&callback=initMap"}

app/views/templates/_other_header.html.haml
.header#header.other-header
  .header__left
    .header__left--logo
      %h1
        = link_to 'OKUTAMA', root_path
  .header__right
    %ul.header__right--ul
      %li
        = link_to 'PHILOSOPHY'
      %li
        = link_to 'MENU'
      %li
        = link_to 'GALLERY'
      %li
        = link_to 'NEWS'
      %li
        = link_to 'ACCESS', access_okutama_index_path
      %li
        = link_to 'CONTACT', new_contact_path